[package]
name = "file_server"
version = "0.2.0"
authors = ["Zacchary Dempsey-Plante <zacc@ztdp.ca>"]
edition = "2021"
license = "WTFPL"
description = "A basic static file server made with Rocket for serving up static files over HTTP."

[dependencies]
clap = "3.0.0-beta.4"
rocket = "0.5.0-rc.1"
