[package]
name = "file_server"
version = "0.1.1"
authors = ["Zacchary Dempsey-Plante <zacc@ztdp.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
rocket = "0.4.6"
rocket_contrib = "0.4.6"
